spring:
  application:
    name: Trix
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${FB_CLIENT_ID}
            client-secret: ${FB_CLIENT_SECRET}
            scope:
            - email
            - public_profile
          